=== DeepanPrashanth/cvbooking/Assign 2/payment.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT payment_details (payment)+>
<!ATTLIST payment_details
  xmlns CDATA #FIXED ''>

<!ELEMENT payment (vehicle_id,amount,modeofpayment,status)>
<!ATTLIST payment
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT vehicle_id (#PCDATA)>
<!ATTLIST vehicle_id
  xmlns CDATA #FIXED ''>

<!ELEMENT amount (#PCDATA)>
<!ATTLIST amount
  xmlns CDATA #FIXED ''>

<!ELEMENT modeofpayment (#PCDATA)>
<!ATTLIST modeofpayment
  xmlns CDATA #FIXED ''>

<!ELEMENT status (#PCDATA)>
<!ATTLIST status
  xmlns CDATA #FIXED ''>

=== DeepanPrashanth/cvbooking/Assign 2/payment.xml
<?xml version="1.0"?>
<?xml-stylesheet href="payment.xsl" type="text/xsl" ?>
<!DOCTYPE payment_details SYSTEM "payment.dtd">
<payment_details>
<payment id="p1">
<vehicle_id>1</vehicle_id>
<amount>RS 5000</amount>
<modeofpayment>Cash</modeofpayment>
<status>Paid</status>
</payment>
<payment id="p2">
<vehicle_id>2</vehicle_id>
<amount>RS 800</amount>
<modeofpayment>Card</modeofpayment>
<status>Pending</status>
</payment>
<payment id="p3">
<vehicle_id>3</vehicle_id>
<amount>RS 1450</amount>
<modeofpayment>GPay</modeofpayment>
<status>Paid</status>
</payment>
<payment id="p4">
<vehicle_id>8</vehicle_id>
<amount>RS 2800</amount>
<modeofpayment>Cash</modeofpayment>
<status>Pending</status>
</payment>
</payment_details>
